# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ae2aa6b80e414318768079fe8aa402c67cbd4d1a6f0261875f6b984815bd8144bbe53e766eb745700836c4ae31e16799240ce549828ff5d39fa169087b5277
  google_client_id: 734098842077-ue21n5p90l354r23ql75hmmd5qtae69r.apps.googleusercontent.com
  google_client_secret: 7qPPS-ZSj6quIaCDqnN-in3o

test:
  secret_key_base: a1f7bbeb7687e48189466821c749dfb890a64a6bd5a916cfc0684a2b47c660e77f88ce5578ab4e6330226d6e57332a8f88c8bd174d14c160884a572a42fbe6b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: 734098842077-ue21n5p90l354r23ql75hmmd5qtae69r.apps.googleusercontent.com
  google_client_secret: 7qPPS-ZSj6quIaCDqnN-in3o